---
name: CI
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PGHOST: localhost
      PGUSER: administrate
      PGPASSWORD: administrate
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: administrate
          POSTGRES_DB: administrate_test
          POSTGRES_PASSWORD: administrate
        ports:
           - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Install dependencies
        run: bundle install
      - name: Setup the environment
        run: cp .sample.env .env
      - name: Setup the database
        run: bundle exec rake db:setup
      - name: Run tests
        run: bundle exec rake
