---
name: CI
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.5, 2.6, 2.7, head, debug]
    continue-on-error: ${{ endsWith(matrix.ruby, 'head') || matrix.ruby == 'debug' }}
    env:
      PGHOST: localhost
      PGUSER: administrate
      PGPASSWORD: administrate
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: administrate
          POSTGRES_DB: administrate_test
          POSTGRES_PASSWORD: administrate
        ports:
           - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Install dependencies
        run: bundle install
      - name: Setup the environment
        run: cp .sample.env .env
      - name: Setup the database
        run: bundle exec rake db:setup
      - name: Run tests
        run: bundle exec rake
